/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormationDto { 
    id?: string;
    title?: string;
    description?: string;
    location?: string;
    date?: string;
    tags?: Array<string>;
}

